name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Pekora
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile pekora.zip
      shell: powershell

    - name: Extract Pekora
      run: Expand-Archive pekora.zip -DestinationPath Pekora
      shell: powershell

    - name: Authenticate Pekora
      run: .\Pekora\ngrok.exe authtoken $Env:PEKORA_AUTH
      env:
        PEKORA_AUTH: ${{ secrets.PEKORA_AUTH }}
      shell: powershell

    - name: Enable RDP (Terminal Services) and firewall
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
      shell: powershell

    - name: Ensure runner user exists and set password
      run: |
        if (Get-LocalUser -Name "runneradmin" -ErrorAction SilentlyContinue) {
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        } else {
          New-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force) -FullName "Runner Admin" -Description "User for RDP"
          Add-LocalGroupMember -Group "Administrators" -Member "runneradmin"
        }
      shell: powershell

    - name: Download Pekora Launcher
      run: Invoke-WebRequest -Uri https://github.com/KoroneX/Korone-Bootstrapper/releases/download/v1.7.0.3/PekoraPlayerLauncher-x64.zip -OutFile PekoraLauncher.zip
      shell: powershell

    - name: Extract Pekora Launcher
      run: Expand-Archive PekoraLauncher.zip -DestinationPath PekoraLauncher
      shell: powershell

    - name: Create Pekora Tunnel (TCP 3389)
      run: .\Pekora\ngrok.exe tcp 3389
      shell: powershell
